version: '3'

services:
  app1:
    build: app
    container_name: node1
    ports:
      - 3001:3000

  app2:
    build: app
    container_name: node2
    ports:
      - 3002:3000

  app3:
    build: app
    container_name: node3
    ports:
      - 3003:3000
 
  nginx:
    build: loadbalancer
    ports:
      - 80:80
